name: ya_tech_flutter
description: "A Flutter implementation of the Y&A Tech website."
publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localization: ^0.3.3
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  material_symbols_icons: ^4.2874.0
  provider: ^6.1.5+1
  scrollable_positioned_list: ^0.3.8
  supabase_flutter: ^2.10.3
  url_launcher: ^6.3.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Enable .arb files for localization
  generate: true

  # Define assets (images, fonts) here
  assets:
    - assets/images/
    - assets/icons/

  # Define fonts
  # fonts:
  #   - family: SpaceGrotesk
  #     fonts:
  #       - asset: assets/fonts/SpaceGrotesk-Regular.ttf
  #       - asset: assets/fonts/SpaceGrotesk-Bold.ttf
  #         weight: 700
